artifact_uri: sqlite///mlflow1.db/1/85dd5433c9cf4573a0197ccd1edf04cf/artifacts
end_time: 1666719685569
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 85dd5433c9cf4573a0197ccd1edf04cf
run_uuid: 85dd5433c9cf4573a0197ccd1edf04cf
source_name: ''
source_type: 4
source_version: ''
start_time: 1666719501562
status: 4
tags: []
user_id: avina
