artifact_uri: sqlite///mlflow1.db/1/a0ba6d9c46264dc1a8f55898d438f87f/artifacts
end_time: 1666717843382
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: a0ba6d9c46264dc1a8f55898d438f87f
run_uuid: a0ba6d9c46264dc1a8f55898d438f87f
source_name: ''
source_type: 4
source_version: ''
start_time: 1666717841274
status: 4
tags: []
user_id: avina
