artifact_uri: sqlite///mlflow1.db/1/bc5581a3b33243968c5ae6adee8f90f9/artifacts
end_time: 1666717407554
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: bc5581a3b33243968c5ae6adee8f90f9
run_uuid: bc5581a3b33243968c5ae6adee8f90f9
source_name: ''
source_type: 4
source_version: ''
start_time: 1666717404612
status: 4
tags: []
user_id: avina
