artifact_uri: sqlite///mlflow1.db/1/aed8928a74ea4dc9ab9479c23efb4d5c/artifacts
end_time: 1666719178934
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: aed8928a74ea4dc9ab9479c23efb4d5c
run_uuid: aed8928a74ea4dc9ab9479c23efb4d5c
source_name: ''
source_type: 4
source_version: ''
start_time: 1666719010069
status: 3
tags: []
user_id: avina
