artifact_uri: sqlite///mlflow1.db/1/107d9b3c4fe64edca646603702f07ec2/artifacts
end_time: 1666716829423
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 107d9b3c4fe64edca646603702f07ec2
run_uuid: 107d9b3c4fe64edca646603702f07ec2
source_name: ''
source_type: 4
source_version: ''
start_time: 1666716829303
status: 4
tags: []
user_id: avina
