artifact_uri: sqlite///mlflow1.db/1/98fbbc6e90bd40abb918cede316d2421/artifacts
end_time: 1666715881851
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 98fbbc6e90bd40abb918cede316d2421
run_uuid: 98fbbc6e90bd40abb918cede316d2421
source_name: ''
source_type: 4
source_version: ''
start_time: 1666715881808
status: 4
tags: []
user_id: avina
