artifact_uri: sqlite///mlflow1.db/1/e340eba4a1fd4928bf3827804f4b1ca3/artifacts
end_time: 1666718454726
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: e340eba4a1fd4928bf3827804f4b1ca3
run_uuid: e340eba4a1fd4928bf3827804f4b1ca3
source_name: ''
source_type: 4
source_version: ''
start_time: 1666718274041
status: 3
tags: []
user_id: avina
