artifact_uri: sqlite///mlflow1.db/1/bc4fbec08e96485a889b81ef5e74ce0a/artifacts
end_time: 1666716850113
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: bc4fbec08e96485a889b81ef5e74ce0a
run_uuid: bc4fbec08e96485a889b81ef5e74ce0a
source_name: ''
source_type: 4
source_version: ''
start_time: 1666716842175
status: 4
tags: []
user_id: avina
