artifact_uri: sqlite///mlflow1.db/1/7baef362d13e4409b210fac49885e1b9/artifacts
end_time: 1666718753591
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 7baef362d13e4409b210fac49885e1b9
run_uuid: 7baef362d13e4409b210fac49885e1b9
source_name: ''
source_type: 4
source_version: ''
start_time: 1666718576751
status: 3
tags: []
user_id: avina
