artifact_uri: sqlite///mlflow1.db/1/9947db3dd3de4e5384bb3839ec961fb9/artifacts
end_time: 1666719178536
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 9947db3dd3de4e5384bb3839ec961fb9
run_uuid: 9947db3dd3de4e5384bb3839ec961fb9
source_name: ''
source_type: 4
source_version: ''
start_time: 1666719010069
status: 3
tags: []
user_id: avina
