artifact_uri: sqlite///mlflow1.db/1/4c08bddc54a644a79be39d46752eabef/artifacts
end_time: 1666718753176
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 4c08bddc54a644a79be39d46752eabef
run_uuid: 4c08bddc54a644a79be39d46752eabef
source_name: ''
source_type: 4
source_version: ''
start_time: 1666718576751
status: 3
tags: []
user_id: avina
