artifact_uri: sqlite///mlflow1.db/1/ac7d95317c8945ccbe40acd8259c5e8b/artifacts
end_time: 1666719447150
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: ac7d95317c8945ccbe40acd8259c5e8b
run_uuid: ac7d95317c8945ccbe40acd8259c5e8b
source_name: ''
source_type: 4
source_version: ''
start_time: 1666719447096
status: 4
tags: []
user_id: avina
