artifact_uri: sqlite///mlflow1.db/1/538bd5edfe1746e2b2460699ab8e5f27/artifacts
end_time: 1666715799778
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 538bd5edfe1746e2b2460699ab8e5f27
run_uuid: 538bd5edfe1746e2b2460699ab8e5f27
source_name: ''
source_type: 4
source_version: ''
start_time: 1666715799638
status: 4
tags: []
user_id: avina
