artifact_uri: sqlite///mlflow1.db/1/fb530c3cd070402aa4c3da00f87b11a4/artifacts
end_time: 1666718753176
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: fb530c3cd070402aa4c3da00f87b11a4
run_uuid: fb530c3cd070402aa4c3da00f87b11a4
source_name: ''
source_type: 4
source_version: ''
start_time: 1666718576751
status: 3
tags: []
user_id: avina
