artifact_uri: sqlite///mlflow1.db/1/5c3fa7f986f94b43b1bcf8e0aa086fd4/artifacts
end_time: 1666717381522
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 5c3fa7f986f94b43b1bcf8e0aa086fd4
run_uuid: 5c3fa7f986f94b43b1bcf8e0aa086fd4
source_name: ''
source_type: 4
source_version: ''
start_time: 1666717381469
status: 4
tags: []
user_id: avina
