artifact_uri: sqlite///mlflow1.db/1/5504c4bbc23e48ffabe0455c5aef79fa/artifacts
end_time: 1666718753176
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 5504c4bbc23e48ffabe0455c5aef79fa
run_uuid: 5504c4bbc23e48ffabe0455c5aef79fa
source_name: ''
source_type: 4
source_version: ''
start_time: 1666718576751
status: 3
tags: []
user_id: avina
