artifact_uri: sqlite///mlflow1.db/1/a3211ed6629a4cfc87d80cee1cd01e4b/artifacts
end_time: 1666717178538
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: a3211ed6629a4cfc87d80cee1cd01e4b
run_uuid: a3211ed6629a4cfc87d80cee1cd01e4b
source_name: ''
source_type: 4
source_version: ''
start_time: 1666717178498
status: 4
tags: []
user_id: avina
