artifact_uri: sqlite///mlflow1.db/1/c21aa1023a7e48718706eecb8788afe8/artifacts
end_time: 1666718454154
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: c21aa1023a7e48718706eecb8788afe8
run_uuid: c21aa1023a7e48718706eecb8788afe8
source_name: ''
source_type: 4
source_version: ''
start_time: 1666718274041
status: 3
tags: []
user_id: avina
